#ifndef FFMPEGMULTIMEDIAPLUGIN_GLOBAL_H
#define FFMPEGMULTIMEDIAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FFMPEGMULTIMEDIAPLUGIN_LIBRARY)
#  define FFMPEGMULTIMEDIAPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FFMPEGMULTIMEDIAPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FFMPEGMULTIMEDIAPLUGIN_GLOBAL_H
